[package]
name = "acn_r"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.23", features = ["macros", "rt-multi-thread"] }
serenity = { default-features = false, features = ["client", "gateway", "model", "rustls_backend", "standard_framework"], version = "0.11.5"}
dotenv = "0.15.0"
chrono = "0.4.23"
log = "0.4.17"
env_logger = "0.10.0"
anyhow = "1.0.68"