version: '3.4'

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ""
      MONGO_INITDB_ROOT_PASSWORD: ""

  lavalink:
    image: mrleo1nid/lavalink
    restart: unless-stopped
    mem_limit: 1024m
    ports:
      - 2333:2333
    environment:
      SERVER_PORT: 2333
