version: '3.4'

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: acn
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      