services:
  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ""
      MONGO_INITDB_ROOT_PASSWORD: ""

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink
    restart: unless-stopped
    mem_limit: 1024m
    ports:
      - 2333:2333
    environment:
      SERVER_PORT: 2333
      LAVALINK_SERVER_PASSWORD: ""
      LAVALINK_SERVER_SOURCES_YOUTUBE: false
      LAVALINK_PLUGINS_0_DEPENDENCY: "dev.lavalink.youtube:youtube-plugin:1.7.1"
      LAVALINK_PLUGINS_0_SNAPSHOT: false
