version: '3.4'

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ""
      MONGO_INITDB_ROOT_PASSWORD: ""
    volumes:
      - mongodb_data:/data/db

  lavalink:
    image: fredboat/lavalink
    restart: unless-stopped
    mem_limit: 2000m
    ports:
      - 2333:2333
    environment:
      SERVER_PORT: 2333
      LAVALINK_SERVER_PASSWORD: ${LAVALINK_PASSWORD}

volumes:
  mongodb_data:
