version: '3.4'

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: acn
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: acn
      POSTGRES_PASSWORD: ${PG_PASSWORD}

  lavalink:
    image: fredboat/lavalink:3.7.8
    restart: unless-stopped
    mem_limit: 400m
    ports:
      - 2333:2333
    environment:
      SERVER_PORT: 2333
      LAVALINK_SERVER_PASSWORD: ${LAVALINK_PASSWORD}
