services:
  mongodb:
    image: docker.io/library/mongo:8.3.2
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4.2.2
    restart: unless-stopped
    mem_limit: 1024m
    ports:
      - 2333:2333
    environment:
      SERVER_PORT: 2333
      LAVALINK_SERVER_PASSWORD: ""
      LAVALINK_SERVER_SOURCES_YOUTUBE: false
      LAVALINK_PLUGINS_0_DEPENDENCY: "dev.lavalink.youtube:youtube-plugin:1.18.1"
      LAVALINK_PLUGINS_0_SNAPSHOT: false
