# fly.toml file generated for acn-r on 2023-04-21T07:41:05-03:00

app = "acn-r"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "gru"
processes = []

[env]

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
