# fly.toml app configuration file generated for acn-r-lavalink on 2023-06-13T04:34:54-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "acn-r-lavalink"
primary_region = "gru"

[http_service]
  internal_port = 2333
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[env]
  SERVER_PORT = 2333